server:
  port: 8081
  servlet:
    context-path: /practice5
spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    platform: org.hibernate.dialect.Oracle12cDialect
    url: jdbc:oracle:thin:@localhost:32769:ORCLCDB
    username: sa
    password: 123456
  jpa:
    database: oracle
    show-sql: true
    hibernate:
      ddl-auto: none
    # create, create-drop, update, [none]
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false